### ISSUE TITLE
Problem with missing trigger_paths/end_paths when using mu2ejobdef with TrkAna. 

### ISSUE THREAD

**Issue by sam-grant** [Mu2e/TrkAna#169]
Attempts to set up a grid submission using TrkAna fcl files with `mu2ejobdef` will result in an error relating to the fact that `physics.trigger_paths `and` physics.end_paths` are not defined. 

For example, when I use the the following template fcl (`run.fcl`)

```
#include "TrkAna/fcl/TrkAnaExtracted.fcl"
services.DbService.purpose: CosmicCRY_best
services.DbService.version: v1_3
```

to generate a tarball for grid submission, using with the command 

`mu2ejobdef --embed run.fcl --override-output-description --auto-description --setup /cvmfs/mu2e.opensciencegrid.org/Musings/TrkAna/v05_03_00/setup.sh --auto-description --dsconf MDC2020ae_best_v1_3 --inputs file_list.txt --merge-factor=1`

the result is 

`Error: please define physics.trigger_paths in the fcl file.`.

You can get around this by appending

```
physics.trigger_paths: [ TrkAnaTrigPath ] 
physics.end_paths: [ TrkAnaEndPath ]
```

to the template fcl, but a more permanent solution might be to include these paths in the source fcl files themselves.

**Comment by sam-grant** [comment]
(I'm working on a PR with a possible solution.)

**Comment by AndrewEdmonds11** [comment]
Now fixed in #171

**Comment by sam-grant** [comment]
Just to note, the fix only applies to `TrkAnaReco.fcl` and `TrkAnaExtracted.fcl` at the moment.

**Comment by AndrewEdmonds11** [comment]
Good point. I'll add an issue to generally tidy up the other fcl files

**Comment by sam-grant** [comment]
I can make the issue and PR if that's easier? There were just a couple of cases where I wasn't sure if what I was doing made sense and wanted to clarify before making a changes.
