### ISSUE TITLE
Create python utility module

### ISSUE THREAD

**Issue by AndrewEdmonds11** [Mu2e/TrkAna#176]
We would like to have some sort of utility module for analyzers to easily interact with the ntuple (see #156 and #158 for examples).

For ROOT, we already have a TrkAnaUtils class; we should have something similar for python. Analyzer should be able to do something like ```import evtntupleutils as enu``` and then use relevant functions to extract information from the ntuple

It would also be good if TrkAnaUtils and the new python module had the same functions with the same arguments

**Comment by AndrewEdmonds11** [comment]
FYI I reported and deleted that spam comment

**Comment by sophiemiddleton** [comment]
https://github.com/Mu2e/TrkAna/pull/177
