### ISSUE TITLE
Consolidate Sim branches

### ISSUE THREAD

**Issue by brownd1978** [Mu2e/TrkAna#89]
Currently there are explict branches for SimParticles related to the candidate track, ie 
demmcsim.
demmcparent.
demmcgparent.
demmcggparent.
demmcgggparent.

These branches have null content when the depth exceeds the actual genealogy (ie when the gggparent SimParticle doesnt exist).

there is the branch for the primary particle
demmcpri.
Whose content is often but not always redundant with the demmcsim.

A more efficient and compact structure would be to have a single branch
demmcsim
with variable-length content, where each entry specifies its position in the genealogy.  That eliminates the need for null content, and a 'valid' flag, as only valid content needs to be filled.   This is also more consistent with the way track fit and VirtualDetector information at various detector locations is now being reported.

**Comment by AndrewEdmonds11** [comment]
Thanks, Dave. That's a nice solution. I will try to get it in as part of v4

**Comment by AndrewEdmonds11** [comment]
Done in #100 and #101
