### ISSUE TITLE
BestCrv isnt needed for Extracted data

### ISSUE THREAD

**Issue by brownd1978** [Mu2e/TrkAna#93]
In extracted data there are 3 overlapping CRV sectors.  BestCrv algorithm is designed to pick the closest match to the reco track, but all 3 test sectors are valid for comparing in extracted mode.  We need a way of saving all 3 Crv sectors in extracted mode.  I suggest we create a new branch of 'selected' crv coincidences, which is a variable-length vector.  We can choose to keep just the 
'best', or we can keep all, or we can keep the 'best 3', as needs be.  That will be more flexible both for extracted and for beam data analysis.

**Comment by AndrewEdmonds11** [comment]
The ```bestcrv``` branch was removed in #104 and replaced with a vector of all crv coincidences so this is no longer an issue
